import type { Metadata } from "next";
import { Lora, Josefin_Sans } from "next/font/google";
import "./globals.css";

const lora = Lora({
  weight: ["400"],
  style: ["normal"],
  subsets: ["latin"],
  display: "swap",
});

const josefin_Sans = Josefin_Sans({
  weight: ["400"],
  style: ["normal"],
  subsets: ["latin"],
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${lora.className} bg-primary`}>{children}</body>
    </html>
  );
}
