import type { Metadata } from 'next';
import { Lora, Josefin_Sans } from 'next/font/google';
import './globals.css';
// import { Span } from 'next/dist/trace';
import Image from 'next/image';

import skinOne from '../assets/images/skin1.webp';
import skinTwo from '../assets/images/skin2.webp';
import skinThree from '../assets/images/skin1.webp';
import ladyOne from '../assets/images/lady1.webp';
import Link from 'next/link';
import { CiSearch } from 'react-icons/ci';

const lora = Lora({
  weight: ['400'],
  style: ['normal'],
  subsets: ['latin'],
  display: 'swap',
});

const josefin_Sans = Josefin_Sans({
  weight: ['400'],
  style: ['normal'],
  subsets: ['latin'],
  display: 'swap',
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const skinImages = [skinOne, skinTwo, skinThree, skinTwo, skinThree, skinTwo];
  const navItems = [
    { title: 'Home', link: '/' },
    { title: 'Shop', link: '/' },
    { title: 'Our Story', link: '/' },
  ];
  const navItemsSecond = [
    { title: 'Blogs', link: '/' },
    { title: 'Contact us', link: '/' },
    { title: 'Cart', link: '/' },
  ];
  const socialLinks = [
    { title: 'FACEBOOK', link: '/' },
    { title: 'INSTAGRAM', link: '/' },
    { title: 'TWITTER', link: '/' },
  ];

  return (
    <html lang="en">
      <body className={`${josefin_Sans.className} bg-primary`}>
        <header className="flex w-full">
          <section className="flex flex-col p-4 gap-y-8 border-r border-b border-black/50 w-[14%] min-w-[220px]">
            <Link href={'/'} className="text-3xl">
              KAHICO <span className="block text-base">Cosmotics</span>
            </Link>
            <div className="flex gap-x-4 items-center justify-between h-full">
              <div className="flex gap-3 flex-col items-center">
                <div className="h-[60px] border-l border-black/50"></div>
                <p className="VER-TEXT text-sm">Scroll - Down</p>
                <div className="h-[60px] border-l border-black/50"></div>
              </div>
              <div className="hide-scrollbar rounded-t-full flex flex-col justify-between gap-y-6 max-h-[54vh] h-full overflow-y-scroll">
                {skinImages.map((img, i) => (
                  <Image
                    key={i}
                    src={img}
                    alt="human hand"
                    className="rounded-t-full max-w-32"
                  />
                ))}
              </div>
            </div>
          </section>
          <section className="flex flex-col border-r border-b border-black/50 w-[43%]">
            <div className="flex justify-between items-center py-4 px-8 border-b border-black/50">
              {navItems.map((item) => (
                <Link key={item.title} href={item.link}>
                  {item.title}
                </Link>
              ))}

              <CiSearch size={22} className="cursor-pointer" />
            </div>
            <div className="flex justify-center items-center gap-y-4 py-4 px-8 h-full">
              <h1 className="header-title text-[6.5rem]">
                Take <span className="text-span block">Care</span> Of Your{' '}
                <span className="text-span">Skin</span> Routine
              </h1>
            </div>
          </section>
          <section className="flex flex-col border-r border-b border-black/50 w-[43%]">
            <div className="flex justify-between py-4 px-8 border-b border-black/50">
              {navItemsSecond.map((item) => (
                <Link key={item.title} href={item.link}>
                  {item.title}
                </Link>
              ))}
            </div>
            <div className="img-container flex justify-center items-center gap-y-4 h-full relative cursor-pointer">
              <div className="overlay w-full h-full absolute bg-span/50 flex justify-center items-center opacity-0">
                <h1 className="text-5xl">
                  KAHICO <span className="block text-base">Cosmotics</span>
                </h1>
              </div>
              <Image src={ladyOne} alt="lady face" className="w-full" />
            </div>
          </section>
        </header>
        <section className="flex items-center justify-between w-full p-4 border-b border-black/50">
          <h2>SOCIAL MEDIA</h2>
          <div className="flex items-center gap-x-8">
            {socialLinks.map((item) => (
              <Link key={item.title} href={item.link}>
                {item.title}
              </Link>
            ))}
          </div>
        </section>
        {children}
        <footer></footer>
      </body>
    </html>
  );
}
